### ISSUE TITLE
Attribute errors on running Maelzel Tutorials -> missing attribute in maelzel\_util.py?

### ISSUE THREAD

**Issue by tqmbanados** [gesellkammer/maelzel#2]
Hello, I am new to Maelzel and am trying to begin with the tutorials. Right from the start in I'm getting the following Exception:
```python
Traceback (most recent call last):
    seq.show()
  File "...\maelzel\core\mobj.py", line 683, in show
    img = self._renderImage(backend=backend, fmt=fmt, scorestruct=scorestruct,
  File "...\maelzel\core\mobj.py", line 864, in _renderImage
    _renderImage(obj=self, outfile=outfile, backend=backend,
  File "...\maelzel\core\mobj.py", line 1772, in _renderImage
    tmpfile, renderer = _renderImageCached(obj=obj, fmt=fmt, config=config, backend=backend,
  File "...\maelzel\core\mobj.py", line 1798, in _renderImageCached
    renderer.write(outfile)
  File "...\maelzel\scoring\renderlily.py", line 1161, in write
    _util.imagefileAutocrop(tempout, cropfile, bgcolor="#ffffff")
AttributeError: module 'maelzel._util' has no attribute 'imagefileAutocrop'
```

It appears to happen when rendering the lilypond file, and I also get the following Error messages from lilypond:
```
[maelzel:lilytools.py:367:renderLily:ERROR] Error while running lilypond, failed to produce a png file: ...\AppData\Local\tmpk9ja2k6b\l6p69pgj.png
[maelzel:lilytools.py:368:renderLily:ERROR] Return code: 1
[maelzel:lilytools.py:369:renderLily:ERROR] Outfile: '...\AppData\Local\tmpk9ja2k6b\l6p69pgj.png', exists: False
[maelzel:lilytools.py:370:renderLily:ERROR] stdout: 

[maelzel:lilytools.py:371:renderLily:ERROR] stderr: 
!! 'C:\Program' is not recognized as an internal or external command,
!! operable program or batch file.
```

Could the _util.py file in the current version be older?

**Comment by tqmbanados** [comment]
It seems the functionality was added in commit ``cabc981``, in both ``_utils.py`` and ``renderlily.py``, but was then moved from ``_utils.py`` to ``_imgtools.py`` in commit ``44923ec``, without adjusting the code in ``renderlily.py``. 
I will see if I can sort this out myself and make a pull request.

**Comment by tqmbanados** [comment]
Fixed the issue, but am running out into further problems, which might be related to my operating system (Windows 11). I will make a new issue for this, and hold off on the Pull request until I solve the bulk of these problems.

**Comment by gesellkammer** [comment]
Windows is supported in the tests so please report anything here.

tqmbanados ***@***.***> schrieb am Mi., 10. Juli 2024, 16:02:
