### ISSUE TITLE
Is there a way to change the logging level?

### ISSUE THREAD

**Issue by cianoc** [gesellkammer/maelzel#4]
Currently it seems to be logging everything, and it's a little excessive. E.g.
`
[maelzel.scoring:quant.py:1364:quantizeMeasure:DEBUG] Measure 4/4 is not filled (events=[«4C 0:1 1♩»]). Filling gaps with silences
[maelzel.scoring:quant.py:1677:_mergeSiblings:DEBUG] Nodes can merge: 
    Node(1/1, 
  «4C 0:1 1♩»
)
    Node(1/1, 
  «rest 1:2 1♩»
)
[maelzel.scoring:quant.py:1680:_mergeSiblings:DEBUG] ---- Merged node:
    Node(1/1, 
  «4C 0:1 1♩»
  «rest 1:2 1♩»
)
`

I was wondering if there is a setting that would change it to something a little saner.

**Comment by gesellkammer** [comment]
maelzel sets the logging level to "DEBUG" for the first run, to be able to debug things if the first installation goes wrong. The second time you run maelzel that should not be the case anymore.
If the loggins keeps showing that means that there must be some other package setting the logging level of the root logger to debug.

**Comment by cianoc** [comment]
Ah that makes sense. It might be helpful to let the new user know - either in the docs, or the initial startup script.

Apologies for the noise.
